name: rescue
description: "A new Flutter project for vehicle rescue services."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.3.0
  location: ^7.0.1
  cupertino_icons: ^1.0.8
  geolocator: ^9.0.2
  permission_handler: ^10.2.0
  http: ^1.2.2

  # Firebase dependencies
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  firebase_database: ^11.1.6
  firebase_storage: ^12.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  # Add any project-specific assets here
  assets:
    - assets/images/logo.png
